; modules/01-digital-io/platforms/pico/platformio.ini

[platformio]
default_envs = pico

[env:pico]
platform         = https://github.com/maxgerhardt/platform-raspberrypi.git
board            = pico
framework        = arduino
board_build.core = earlephilhower
monitor_speed    = 115200
build_flags      =
  -Wall -Wextra
  -DSERIAL_BAUD=115200
