; modules/01-digital-io/platforms/arduino-uno/platformio.ini

[platformio]
default_envs = uno

[env:uno]
platform      = atmelavr@^4.2.0
board         = uno
framework     = arduino
upload_speed  = 115200
monitor_speed = 9600
build_flags   =
  -Wall -Wextra -Wpedantic
  -DSERIAL_BAUD=9600
